### ISSUE TITLE
show prefixes on diagram

### ISSUE THREAD

**Issue by VladimirAlexiev** [EKGF/dprod#94]
In the diagram in sec https://ekgf.github.io/dprod/#data-product-dprod-model please :
- show the prefix of each term
- spell the actual class name: `Data Product` -> `dprod:DataProduct` 
- fix the misspelling `conformTo` -> `dct:conformsTo`

**Comment by joshcornejo** [comment]
Here is a proposed new diagram 

![baseline](https://github.com/user-attachments/assets/5b72e099-736f-4666-b9ce-e9fab047644a)

@jgeluk

**Comment by VladimirAlexiev** [comment]
I like this diagram better, but I'll post an issue about some ontology issues

**Comment by rivettp** [comment]
The new diagram is a bit misleading in that we don't define our own subclass of Dataset etc, just a new property with Dataset as domain

**Comment by rivettp** [comment]
We'll update the diagram - @andrea-gioia

**Comment by joshcornejo** [comment]
updated 

![latest](https://github.com/user-attachments/assets/daccee76-da46-4610-a2cb-5590c81c96bb)

**Comment by VladimirAlexiev** [comment]
@joshcornejo nice!
The link for isAccessServiceOf bears a wrong name

**Comment by joshcornejo** [comment]
Maybe like this:

![DPROD](https://github.com/user-attachments/assets/c2b36433-63cf-4468-9805-d23851a33741)

**Comment by andrea-gioia** [comment]
Hi, the last one posted by @joshcornejo  works for me, but I suggest removing the ODRL part to keep it more compact and focused on DPROD. What do you think? @rivettp @VladimirAlexiev

**Comment by joshcornejo** [comment]
![DPROD](https://github.com/user-attachments/assets/a809ca5e-7abe-452d-bbb4-11c40441cc69)

**Comment by andrea-gioia** [comment]
Thanks, @joshcornejo . For now, we can use the last image you shared, but it would be great to have the source file as well, so we can edit it in the future. The current image was created with draw.io, and the source file is available in the assets folder along with the generated SVG. 

@joshcornejo , would you be able to convert the image into a draw.io diagram? If that's not possible at the moment, we can use the current image for now and open a separate issue to remind us to redesign it in draw.io later so that the source is available in the repository. Let me know. 

Thanks!

**Comment by joshcornejo** [comment]
I've generated SVG + drawio ... but:

Uploads are disabled.
File uploads require push access to this repository.

**Comment by rivettp** [comment]
Here is the OMG FTF issue https://issues.omg.org/browse/DPROD-10
